#!/bin/bash
#
# 1. copy into /etc/cron.daily/ or /etc/cron.weekly
# 2. adjust the PROJECT_PATH
#

cd PROJECT_PATH

docker compose exec -T nginx certbot renew
docker compose exec -T nginx nginx -s reload
